plugins { id 'dev.architectury.loom-no-remap' }
base { archivesName = rootProject.archives_base_name }

dependencies {
    minecraft libs.minecraft
    implementation libs.fabric.loader
    implementation libs.fabric.api
    compileOnly libs.modmenu
    def seamlessApiFabric = files(rootProject.file("../seamless-api/fabric/build/libs/seamless-api-${libs.versions.seamless.api.get()}-fabric.jar"))
    seamlessApiFabric.builtBy gradle.includedBuild('seamless-api').task(':fabric:jar')
    implementation seamlessApiFabric
    implementation project(':common')
}

loom {
    mods {
        swordthrow {
            sourceSet sourceSets.main
            sourceSet project(':common').sourceSets.main
        }
    }
}

fabricApi {
    configureTests {
        createSourceSet = true
        modId = 'swordthrow-gametest'
        enableGameTests = true
        enableClientGameTests = false
        eula = true
    }
}

dependencies { gametestImplementation project(':common') }

def metadataVersion = project.version.toString()
processResources {
    inputs.property 'version', metadataVersion
    filesMatching('fabric.mod.json') { expand version: metadataVersion }
}

tasks.named('jar', Jar) {
    from project(':common').sourceSets.main.output
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    archiveFileName = "${rootProject.archives_base_name}-${project.version}-fabric.jar"
}
tasks.named('sourcesJar', Jar) {
    from project(':common').sourceSets.main.allSource
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    archiveFileName = "${rootProject.archives_base_name}-${project.version}-fabric-sources.jar"
}
