[versions]
minecraft = "1.20.1"
java = "17"
architectury-plugin = "3.5.169"
architectury-loom = "1.17.493"
fabric-loader = "0.19.5"
fabric-api = "0.92.12+1.20.1"
fabric-minimum-api = "0.92.12"
fabric-maximum-api-exclusive = "0.93.0"
forge = "1.20.1-47.4.26"
seamless-api = "2.0.2+mc1.20.1"
modmenu = "7.2.2"
junit = "5.12.2"
mixin = "0.17.3+mixin.0.8.7"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
forge = { module = "net.minecraftforge:forge", version.ref = "forge" }
seamless-api-common = { module = "io.github.derkottersberg:seamless-api-common", version.ref = "seamless-api" }
seamless-api-fabric = { module = "io.github.derkottersberg:seamless-api-fabric", version.ref = "seamless-api" }
seamless-api-forge = { module = "io.github.derkottersberg:seamless-api-forge", version.ref = "seamless-api" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
mixin = { module = "net.fabricmc:sponge-mixin", version.ref = "mixin" }

[plugins]
architectury = { id = "architectury-plugin", version.ref = "architectury-plugin" }
loom = { id = "dev.architectury.loom", version.ref = "architectury-loom" }
